const actionsTypes = {
  ADICIONAR_TAREFA: "ADICIONAR_TAREFA",
  REMOVER_TAREFA: "REMOVER_TAREFA",
  EDITAR_TAREFA: "EDITAR_TAREFA",
  FILTRAR_TAREFA: "FILTRAR_TAREFA",
  CONCLUIR_TAREFA: "CONCLUIR_TAREFA",
};

export { actionsTypes };
